[package]
name = "sentinel_grid_chain"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
time = "0.3"
rand = "0.8"
flate2 = "1.0"
aes-gcm = "0.10"
tokio = { version = "1", features = ["full"] }

[build-dependencies]
cc = "1.0"
